### ISSUE TITLE
Function name expression

### ISSUE THREAD

**Issue by J-Fobos** [ccleaud/ProgressABL-for-Notepad-plusplus#4]
Hello,
There are small bug in functionList.xml.
Function name has shown incorrect, when before procedure/funktion keyword there are spaces.
You can see this on screenshot http://ipic.su/img/img7/fs/111.1451487372.png

I suggest change tag <nameExpr> on expr="\<[^:\r\n]*" for fix this bug.

**Comment by ccleaud** [comment]
Hello,

Thanks for reporting this and thanks for the suggestion.
I'll try to correct soon.

Regards
